 const PLAYER_API_HOST = 'http://localhost:3001/api/players';
 const FAVORITE_PLAYER_URL= `${PLAYER_API_HOST}/favorites`;
 const ADD_FAVORITE_PLAYER_URL = `${PLAYER_API_HOST}/removeFavorite`;
 const REMOVE_FAVORITE_PLAYER_URL = `${PLAYER_API_HOST}/addFavorite`;

 export { PLAYER_API_HOST, FAVORITE_PLAYER_URL, ADD_FAVORITE_PLAYER_URL, REMOVE_FAVORITE_PLAYER_URL };

